workspace(name = "score_bazel_tools_cc_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# This workspace loads local dependencies from score_bazel_tools_cc for testing purposes.
# Ideally each user workspace will have its own set of local dependencies.

local_repository(
    name = "score_bazel_tools_cc",
    path = "..",
)

load("@score_bazel_tools_cc//bazel:github.bzl", "github_url")

##########################
# Internal dependencies. #
##########################

load("@score_bazel_tools_cc//third_party/bazel_skylib:bazel_skylib.bzl", "bazel_skylib")

bazel_skylib()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "rules_shell",
    sha256 = "e6b87c89bd0b27039e3af2c5da01147452f240f75d505f5b6880874f31036307",
    strip_prefix = "rules_shell-0.6.1",
    url = github_url("bazelbuild/rules_shell/releases/download/v0.6.1/rules_shell-v0.6.1.tar.gz"),
)

load("@rules_shell//shell:repositories.bzl", "rules_shell_dependencies", "rules_shell_toolchains")

rules_shell_dependencies()

rules_shell_toolchains()

load("@score_bazel_tools_cc//third_party/rules_python:rules_python.bzl", "rules_python")

rules_python()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

http_archive(
    name = "bazel_tools_python",
    sha256 = "8ed81261f513c1f7a2da6ce91e66bb88ccd03532ad7f7ecb08678e56e632f4b1",
    strip_prefix = "bazel-tools-python-0.1.3",
    url = github_url("eclipse-score/bazel-tools-python/archive/refs/tags/v0.1.3.tar.gz"),
)

load("@bazel_tools_python//third_party:python_toolchains.bzl", bazel_tools_python_python_toolchains = "python_toolchains")

bazel_tools_python_python_toolchains()

load("@bazel_tools_python//third_party:python_pip_parse.bzl", bazel_tools_python_python_pip_parse = "python_pip_parse")

bazel_tools_python_python_pip_parse()

load("@bazel_tools_python//third_party:python_pip_hub.bzl", bazel_tools_python_python_pip_hub = "python_pip_hub")

bazel_tools_python_python_pip_hub()

############################################
# Dependencies from score_bazel_tools_cc. #
###########################################

load("@score_bazel_tools_cc//third_party:dependencies.bzl", score_bazel_tools_cc_dependencies = "dependencies")

score_bazel_tools_cc_dependencies()

load("@score_bazel_tools_cc//third_party:python_toolchains.bzl", score_bazel_tools_cc_python_toolchains = "python_toolchains")

score_bazel_tools_cc_python_toolchains()

load("@score_bazel_tools_cc//third_party:python_pip_parse.bzl", score_bazel_tools_cc_python_pip_parse = "python_pip_parse")

score_bazel_tools_cc_python_pip_parse()

load("@score_bazel_tools_cc//third_party:python_pip_hub.bzl", score_bazel_tools_cc_python_pip_hub = "python_pip_hub")

score_bazel_tools_cc_python_pip_hub()

###################
# LLVM toolchain. #
###################

http_archive(
    name = "toolchains_llvm",
    canonical_id = "v1.4.0",
    sha256 = "fded02569617d24551a0ad09c0750dc53a3097237157b828a245681f0ae739f8",
    strip_prefix = "toolchains_llvm-v1.4.0",
    url = github_url("bazel-contrib/toolchains_llvm/releases/download/v1.4.0/toolchains_llvm-v1.4.0.tar.gz"),
)

load("@toolchains_llvm//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@toolchains_llvm//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "15.0.2",
    stdlib = {"linux-x86_64": "stdc++"},
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()
